version: "3"

services:
  server:
    build: .
    volumes:
      - .:/app
      - $GOPATH/pkg/mod:/go/pkg/mod
    ports: 
      - 8000:80
    environment: 
      - PORT=80
      - GOPATH=/go
  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: ecommerce 

    volumes:
      - postgres-volume:/var/lib/postgresql/data

volumes:
  postgres-volume: {}
