// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package types

import (
	"github.com/Antuans-Tavern/ecommerce-backend/pkg/database/model"
)

type Login struct {
	Token string      `json:"token"`
	User  *model.User `json:"user"`
}

type Register struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Name     string `json:"name"`
	Lastname string `json:"lastname"`
}
