name: Go

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres 
          POSTGRES_PASSWORD: secret
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: copy enviroment file
      run: cp .env.testing .env

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
  deploy:
    needs: test
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: build --rm-dist --snapshot
      - 
        name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: dist/ecommerce-backend_linux_amd64/ecommerce
          target: ecommerce
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
